services:
  app:
    build:
      context: ./
      dockerfile: ./builds/docker/Dockerfile
      args:
        APP_DOCKER_IMAGE: ${APP_DOCKER_IMAGE}
    image: leadbest/backend-app
    volumes:
      - ./:${WORKSPACE_DIR}
    working_dir: ${WORKSPACE_DIR}
    environment:
      - NODE_PATH=/usr/local/lib/node_modules
    command:
      - php
      - artisan
      - octane:start
      - --server=swoole
      - --host=0.0.0.0
      - --port=80
      - --watch
    ports:
      - 80:80
  database:
    ports:
      - 3306:3306
  redis:
    ports:
      - 6379:6379
  smtp:
    image: axllent/mailpit:latest
    ports:
      - 8025:8025
    networks:
      - getoken
  swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - ./storage/api-docs:/usr/share/nginx/html/api-docs:ro
    environment:
      URLS: |
        [
            { name: "api-v1", url: "/api-docs/api-v1.yaml" }
        ]
      URLS_PRIMARY_NAME: api-v1
      DOC_EXPANSION: none
    ports:
      - 8080:8080
    networks:
      - getoken
